# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-anime-secret
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:rRUNjqfjRdoWnuzZRxExTKUxJizOPRT10Vw+Xiu5MDE=,iv:sgKxoA/oZQXn/rD7kJamO3hMfjsQYSKxBhs2IwkUmi4=,tag:3WbEJfjrEJOWHB6WFSfbWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd0xTOXRJcE1IaWpHWjI3
            VUMxdEkrNXhxZ1IzaFl0U2tYb2dYQWtzQlhZCkNMUDdFRExHWDFGYlYrOENid09Q
            LzEwUXlPOEYyeDlDcU9xK1Z5L1czUWsKLS0tIFpmUHgzYWY4SERrRmJvM2RhUUlz
            bzVDTXo0RFZUQk9pNDJpQk1xREdLSDQK8ZMF6xiah9bwFsLIiup8ax09RGGUSxyn
            E94t9s8PdOeLdcfx4wUKUGjIuL1WAN77dxkVGoAseHxRgdpRK/4PFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T19:01:47Z"
    mac: ENC[AES256_GCM,data:e8BeXxHVXEooeAvfX3WDDmwPgF6JG+JX0jKsyftMoNVCKpRWWGl67pcWFEE5fvcmsn75BiaBgLXI02XhNqU4eRJ/Ge8Q6zg4O7gWhs7TsvryZr5kwDy1QpFsASH46qcLe7TTXXZMrUmjZyywQoWDrBM3U+7t/V7YNtsdehcy9q8=,iv:ucFsn36GhZQtUtHNjTGvC+aVr+c/FLDx2lFSwqJtah0=,tag:X0pZv0zTKdJG2Asm/2+cgQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
