# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:2gPRRReroF3xojNelLcyJsD/VP7JW+TcEvHcOKCC7Hk=,iv:y2cR8YURYlxk8vcDVJtf92DKBk0veMlc5r7ZcELSPbo=,tag:guKE53/vgDvctDZNTbqmNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaE92cDN2NUlYaXhUNTdG
            TUQ4bjRNdDJJZ2FVVFhROVBVVWM3OHIvckFRCkxWamQxNUxmUGRxRThkUXd3cmRl
            MHFZM1BFOEtOeTBqejRXaSs4c3VYKzQKLS0tIEdXRldwQVFPUTFTL1J0UkE3M3I1
            OFQyTHdtKzY3WG55aHJxbzkwbDlod0kKVyBQ1K3dvkmicM1p+ic59SZD90Qkenuy
            FQdsNSAQwM98+Y4PK7QOf5gMuDp4jSIyAR6ML0pWnHVaHyJjTl/fcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T21:49:10Z"
    mac: ENC[AES256_GCM,data:LtQ/hW4CSCRkkhiXSgLooYXVh5Zyl/pLFxi0nemcY1HELtCvV0GJJ0tWovps1PlXBrvNkTLRA5lzyMUuJm/FBoJs5nqamKV7Vw5KFppFmSJMb02FWIvbwgUucIl/vWca/h6uKMhB6r2W0J+0bpA8RknN18E8dT7aQcSzWh41E6o=,iv:x9HZPAKk0LdiEmPO5NYoKLrV4vvKMB8tSBtcBjszieE=,tag:3caO2VXn0EslLMkHzXK55Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
