# TODO set net.ipv4.ping_group_range to allow ICMPv4 proxying (default '0 1' == block). v6 gives "socket: permission denied"
# securityContext:
#   runAsGroup:
# set --post-quantum to enable post-quantum crypto
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/pl4nty/cloudflare-kubernetes-gateway//config/default?ref=v0.8.1
# - github.com/pl4nty/cloudflare-kubernetes-gateway//config/prometheus?ref=v0.8.1
- ./gatewayclass.yaml
- ./gateway.yaml
- ./secrect.sops.yaml
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: network
  target:
    kind: Service
    name: image-metrics-service
