---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name postgres-server-ca
spec:
  isCA: true
  commonName: postgres-ca
  secretName: *name
  subject:
    countries:
      - VN
    organizations:
      - homelab-cluster
    organizationalUnits:
      - postgres
  usages:
    - cert sign
    - crl sign
  nameConstraints:
    critical: true
    permitted:
      dnsDomains:
        - postgres-cluster-rw
        - postgres-cluster-rw.database
        - postgres-cluster-rw.database.svc
        - postgres-cluster-rw.database.svc.cluster.local
        - postgres-cluster-r
        - postgres-cluster-r.database
        - postgres-cluster-r.database.svc
        - postgres-cluster-r.database.svc.cluster.local
        - postgres-cluster-ro
        - postgres-cluster-ro.database
        - postgres-cluster-ro.database.svc
        - postgres-cluster-ro.database.svc.cluster.local
  duration: 8766h # 1 year
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Never
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
    group: cert-manager.io
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: &name postgres-server-ca
spec:
  ca:
    secretName: *name