---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name postgres-server-cert
spec:
  commonName: postgres
  dnsNames:
    - postgres-cluster-rw
    - postgres-cluster-rw.database.svc
    - postgres-cluster-rw.database.svc.cluster.local
    - postgres-cluster-r
    - postgres-cluster-r.database.svc
    - postgres-cluster-r.database.svc.cluster.local
    - postgres-cluster-ro
    - postgres-cluster-ro.database.svc
    - postgres-cluster-ro.database.svc.cluster.local
  subject:
    countries:
      - VN
    organizations:
      - homelab-cluster
  usages:
    - server auth
  duration: 720h # 1 month
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Never
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  issuerRef:
    name: postgres-server-ca
    kind: Issuer
    group: cert-manager.io
  secretName: *name
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name postgres-client-cert
spec:
  secretName: *name
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: postgres-client-ca
    kind: ClusterIssuer
    group: cert-manager.io