---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres-cluster
spec:
  retentionPolicy: "7d"
  configuration:
    destinationPath: "s3://${S3_POSTGRES_BUCKET}/"
    endpointURL: ${S3_POSTGRES_STORAGE}
    s3Credentials:
      accessKeyId:
        name: cnpg-objectstore
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-objectstore
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: zstd
      maxParallel: 8
    data:
      compression: bzip2