---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-exporter
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.48.0
  url: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: node-exporter
  values:
    fullnameOverride: node-exporter

    image:
      registry: quay.io
      repository: prometheus/node-exporter

    prometheus:
      monitor:
        enabled: true
        jobLabel: app.kubernetes.io/instance

        relabelings:
          - action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: kubernetes_node
          - action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: nodename
          - action: replace
            regex: (.*)
            replacement: $1.tuilkhanh.internal:9100
            sourceLabels:
              - kubernetes_node
            targetLabel: instance

    resources:
      requests:
        cpu: 23m
        memory: 64M
      limits:
        memory: 64M

    hostNetwork: false
