---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/pl4nty/cloudflare-kubernetes-gateway//config/default?ref=v0.8.1
# - github.com/pl4nty/cloudflare-kubernetes-gateway//config/prometheus?ref=v0.8.1
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: network
  target:
    kind: Service
    name: image-metrics-service
