# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cleanrr-secret
stringData:
    CLEANRR_SERVERS__RADARR__API_KEY: ENC[AES256_GCM,data:zOLmSWhz7/EMPU3NAIrRyH8i/HnFTj7bq1T6Y79Q5x0=,iv:zYiN1dnRduhmkcDKXevl6epQnHZ5GHw/VOzPTGHITLc=,tag:cIWxcW84gOasR9dPG3P7/g==,type:str]
    CLEANRR_SERVERS__SONARR__API_KEY: ENC[AES256_GCM,data:SM0no3PBDTx/F7UxOPw2XTDkcR4JbWj4/hDUkxT+ERU=,iv:sBVcfV0PCsOBV0p5klhOsiLz7gZoK95xYaIfycqsjm8=,tag:q7jLn9l0NN7Sdoh9oMxyrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbk9DbXFkczV5K2lhOVBB
            V2wwZmR2SDBvL0RndjB2cXQ5M3IxazBPTUVBClZPWldyUTJod3hpeTd6VCtCbTF1
            UFRBT2NLVDFlT1lCYUdQeTFQM3pHMzgKLS0tIGtzTXNpYTliblBaUzlkMUhRNlRx
            RFdzd3Z4REJLeWFHOWY4OFFUalVMencKbXMn+gemHrlbSQUW67fe3vKgY3E/0DG6
            yl2CtXBXWHpHR9pn5QZa7wsEJDLP5yOLnwgbCFv1bZqGfeRjuBYCSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T12:05:04Z"
    mac: ENC[AES256_GCM,data:mE+hcGbT4PAcLV1DBSVOCNrcS7hVksQ6FHiAZ1uunMgLzmR7c5o4ICMSpTRjsLcoGE/a33gU49Vr8qb/wwZ+tSr/Ay3P1c2w1Z2HSrtWtT4BUQ8uCW6SwPy+KDCm0w8LPnV1CxEhrZG52YAs1xfoBgVVztjlYCrrAz5duW0IHws=,iv:OkSYB8uqvvrFsnd2zr79anuuA0SRx+y2fxh07jjFzF8=,tag:sKFdFKzIDkaHxEe4rkysGQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
