---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app api-valkey
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: api-valkey
  values:
    controllers:
      valkey:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.0
            args:
              - --appendonly
              - yes
              - --save
              - "60 1"
              - --save
              - "300 100"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1Gi

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.1.109
        ports:
          http:
            port: 6379

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 8Gi
