apiVersion: v1
kind: Secret
metadata:
  name: cs-agent-mysql
stringData:
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:0/kkUP748YTUbpbXAC83fw==,iv:oKfHYOV8ty7mQhAJ8zO4u9qgMCiHtKVyVAeHf3WR1cM=,tag:Vjxtwk3j6vSXmZOR8+NXaA==,type:str]
  MYSQL_PASSWORD: ENC[AES256_GCM,data:AONCljXeEM5oQMJ98fXy/g==,iv:yZ3wh7+hVQXoKVJz9QijCK/YXGYLDfuOqjY8VO/Olk4=,tag:J93YUjFZgO3HCByj3MCfWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMUthaFZqYUtZekIxcjFK
        SlozRzdmT3NRSzBhYkVsY1hUdjZrdUpBcUY0Cm5pcVZPSWRpRUxmY0RTeFQ3NjJP
        ZjBzVG1jWXcwaTYrdFE2SUVQQmphMWcKLS0tIFBlWC9CZUJXMWRRSjBobDZCSS9D
        eGxTeXQyekZuL3o1UlZWdVRFckE2bWcKy4hjRMoaE0tfGuhCGR6gBAw24zpq7PkF
        T/mknLXXuVCbVxafKKeMCJGUESrtFSWnpLAHOHUHjRqF7dSrlI/pOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T20:02:59Z"
  mac: ENC[AES256_GCM,data:ZM8UDACSRn0JB4sCUclz4DX6zvxKi3K8o1oXl7Y6tuAyWAbQaEGM1fuM/v5cGvuz+pHsm+6vQ5Po0BVSmTTGiXRxN/fC1ZFoJOuhtp5fwtUlOrOoAel7y2PieWSYj4D/xMRNHVEpBmn9/OA47+6kYFkEShqEk8MwHtrzb9BJC7w=,iv:is3d9r4xJzd+ZLtSks4OMVPC/J+29pE8czSqZ68qT9s=,tag:NCUGnHy+wHI61U4RazWyeQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
