---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: k8s-gateway
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.4.0
  url: oci://ghcr.io/home-operations/charts-mirror/k8s-gateway
  verify:
    provider: cosign
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: k8s-gateway
    domain: "${SECRET_DOMAIN}"
    ttl: 1
    image:
      registry: ghcr.io
      repository: soliddowant/k8s_gateway
      tag: v0.4.0-37-g9b0bbe7
    service:
      type: LoadBalancer
      port: 53
      annotations:
        lbipam.cilium.io/ips: ${CORE_DNS_VIP}
    # watchedResources: ["Gateway", "HttpRoute", "Service"]

