---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app it-tools
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: it-tools
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      app:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/corentinth/it-tools
              tag: 2024.10.22-7ca5933
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 25Mi
              limits:
                memory: 100Mi

    service:
      app:
        controller: app
        ports:
          http:
            port: 80

    route:
      app:
        parentRefs:
          - name: external-gateway-cilium
            namespace: network
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        rules:
          - backendRefs:
              - identifier: app
                port: 80
