# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-repository-secret
stringData:
  AWS_ENDPOINT: ENC[AES256_GCM,data:8d00MfoUgWHoEndeUciWrekv3468+sXUuyV4leX86xwa6grNp8esXR5NTDwuNAQTvyjj9NbGB5rA,iv:8qfUhJT9tpwa466IW8U76z2FpTqasqoFs7gynYEW8v0=,tag:B5/kjw3R0MqMHtrYlO7GLw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0yUYTHFq88f8d0Y3AG2FRw4LarHDhIy7z90+00EhzDM=,iv:B2+8MJgdaPPvMFn8OeE+hn7y/hzRT5hRWKSBAAwGk3M=,tag:Pgw+BuFV1HyUtvhHqzxNHw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WbsWxDN9Hx0YWQlcw81rDs3N2OO99xJ/Dbue2C5Wo5S9zUHT80jEb23cSRDSFHY7XdlHqxu4fsBXosJC2/vPDA==,iv:rpppwBMCy2ebOUvrG1rCYBMMWANrssUBIfegUhOD0F4=,tag:cbx6hTIf6IomReDHZxlwqw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:OzsMjYF/VjgKIvdjKZvd0uFp,iv:Wx3+SbUFZBeYc63iic5jk42pV9KQnBoEVhI8qcLmbcQ=,tag:GSIWXvcRt0wMTjiUdQtV5w==,type:str]
# yamllint disable
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRmdyTFNtUkpyVE1LOWh0
        byt6YzBtaVVtdGMveFJKSkpUbHd0U3RiOFdvCmF2L0cvem5GMUQyaThuZVJYbmVl
        VnBhY2F3d1kzWGtwdWxVelBWdjdDaVUKLS0tIC84SDAxcHBvZEpSUmtrR1hpbCt4
        c0dvZUNuU0VvUGpnaUxjMFdjSHJIVFUKPD0HJ8V24HaaClZN3tzSTCztA9WrxuEF
        XnzK+oe8KhA9ozFGBsqhBnOYXRFMzTR3rOskjMn1xkmXls4zAOzzbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T12:26:01Z"
  mac: ENC[AES256_GCM,data:ccw4ySQbZnKI5VCeOLfIhNUACyns41e5ERoWYh3wmPlC5ValT5yp+fMCmTYGU0zmag2GTZAmOQbC7whquzbep4uWYhLt5ThqpdvTyq8DpajvJpLcRK7rEJIenI+WDV14WPK9n6rLXLUe2A4HWWoHzqWYtpYqw8sL/H6SiMJkF7Y=,iv:lCATOj4fgA8+DLgomutHhJ8b1s+a52tWvyS9JpRNorA=,tag:r38boGwxq7RJab6dR8ISAg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: nas-repository-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SDwvuOtH/Mw0wMPMaHbk+ngLexC1bdpfopM=,iv:hiQkq1fEqLEOwCOzWRuU180EjiSLJZpIonK7jXRIcDA=,tag:HLH1vcOzlqFT1/kkHAskXg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:c1zFoEqgwOdfWtS6AI7gyYx2iLd/gk+jU13Ogd4+gRkCMLut0EBWfrDPs5Qr0xky3DRdD2MWKMZSt/3qsrqRvw==,iv:zSDHjJ4ItpO9IDm8GbSZJkkJbHwGz+L4IumZLDxMmOU=,tag:SxElUCXCZAtMAZofVm4G6w==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:36z6Vsdt+JMH5Er80El9g6gE,iv:+VqzlGVFgEpTW0Wuo1RNs44K9QIcr0L2Comn/3xKtqg=,tag:7Mtlo1KrNnTr1jnt10z4ug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRmdyTFNtUkpyVE1LOWh0
        byt6YzBtaVVtdGMveFJKSkpUbHd0U3RiOFdvCmF2L0cvem5GMUQyaThuZVJYbmVl
        VnBhY2F3d1kzWGtwdWxVelBWdjdDaVUKLS0tIC84SDAxcHBvZEpSUmtrR1hpbCt4
        c0dvZUNuU0VvUGpnaUxjMFdjSHJIVFUKPD0HJ8V24HaaClZN3tzSTCztA9WrxuEF
        XnzK+oe8KhA9ozFGBsqhBnOYXRFMzTR3rOskjMn1xkmXls4zAOzzbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T12:26:01Z"
  mac: ENC[AES256_GCM,data:ccw4ySQbZnKI5VCeOLfIhNUACyns41e5ERoWYh3wmPlC5ValT5yp+fMCmTYGU0zmag2GTZAmOQbC7whquzbep4uWYhLt5ThqpdvTyq8DpajvJpLcRK7rEJIenI+WDV14WPK9n6rLXLUe2A4HWWoHzqWYtpYqw8sL/H6SiMJkF7Y=,iv:lCATOj4fgA8+DLgomutHhJ8b1s+a52tWvyS9JpRNorA=,tag:r38boGwxq7RJab6dR8ISAg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
