---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
# components:
#   - ../../flux/components/common
resources:
  - ./namespace.yaml
  - ./jellyfin/ks.yaml
  - ./immich/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./filebrowser/ks.yaml
