[env]
JUST_UNSTABLE = "1"
FLATE_PATH = '{{config_root}}/kubernetes/flux/cluster'
KUBECONFIG = '{{config_root}}/kubeconfig'
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = '{{config_root}}/talosconfig'
SOPS_AGE_KEY_FILE  = '{{config_root}}/age.key'

[settings]
pipx.uvx = true

[tools]
"aqua:astral-sh/uv" = "latest"
"aqua:google/yamlfmt" = "latest"
"github:home-operations/flate" = "latest"
"github:mitsuhiko/minijinja" = "2.21.0"
sops = "3.13.3"
jq = "1.8.2"
just = "1.57.0"
lefthook = "2.1.10"
oxfmt = "0.61.0"
shellcheck = "0.11.0"
talos = "1.14.0-beta.1"
yq = "4.53.3"
gum = "0.17.0"
helmfile = "1.7.3"

[hooks]
postinstall = "lefthook install"