# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:2gPRRReroF3xojNelLcyJsD/VP7JW+TcEvHcOKCC7Hk=,iv:y2cR8YURYlxk8vcDVJtf92DKBk0veMlc5r7ZcELSPbo=,tag:guKE53/vgDvctDZNTbqmNA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaE92cDN2NUlYaXhUNTdG
        TUQ4bjRNdDJJZ2FVVFhROVBVVWM3OHIvckFRCkxWamQxNUxmUGRxRThkUXd3cmRl
        MHFZM1BFOEtOeTBqejRXaSs4c3VYKzQKLS0tIEdXRldwQVFPUTFTL1J0UkE3M3I1
        OFQyTHdtKzY3WG55aHJxbzkwbDlod0kKVyBQ1K3dvkmicM1p+ic59SZD90Qkenuy
        FQdsNSAQwM98+Y4PK7QOf5gMuDp4jSIyAR6ML0pWnHVaHyJjTl/fcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T20:36:20Z"
  mac: ENC[AES256_GCM,data:1KkAqNSsXRS/JwgeXBsUtVW6RQ5k9g6CIpKM56jFwT4RNkd+Eh/I0YRKHYKSqd9c2ZqTA1KSOscHsKPtyu9GfEZeXLWDhFbC9pbCSJW2G3klZRsQCg1pk9/U7nriKJkKuhgZ6euWNPiruUpMqNSydfMRTRMMkE3WqTPVPTRB+ts=,iv:jjy6/U6zpCPZQ4OO0O6C8Gx30obTM0P7RPA37xKKZvE=,tag:KjW5Z0fWGlrYHCZ5FOa2sw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
