---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rabbitmq
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: rabbitmq
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      rabbitmq:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/library/rabbitmq
              tag: 4
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 101m
                memory: 25Mi

    service:
      app:
        ports:
          http:
            port: 5672
