---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/cnpg/app-template
  dependsOn:
    - name: kopiur
      namespace: kopiur-system
    - name: postgres-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/security/vaultwarden/app
  postBuild:
    substitute:
      APP: vaultwarden
      VOLSYNC_CAPACITY: 1Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  timeout: 5m
  wait: false
