---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard
spec:
  secretName: tls-adguard
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: dns.tuilakhanh.id.vn
  dnsNames:
    - dns.tuilakhanh.id.vn
  privateKey:
    rotationPolicy: Always
