---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250M
  storageClassName: openebs-hostpath



