---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: openebs-hostpath
