---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-work
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
