# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: deduparr-secret
stringData:
  DEDUPARR_RADARR_MOVIES_API_KEY: ENC[AES256_GCM,data:glKdhA3DMqPQwPNkHaG5e7Asz3nU4+ISyJ7z+lq9q2E=,iv:q95TB6OLIyz3IpRvzwfTuUMnpvhzvYNY0OSUrEcBYCA=,tag:QmxYfNKKWDzcpMfK534oXQ==,type:str]
  DEDUPARR_SONARR_SERIES_API_KEY: ENC[AES256_GCM,data:HHTHWwOy3fwsPxQHQS/Z9yQlCAO6bkMES41Auivh+6o=,iv:D8WqR1tFSO7b8clyZoyNg2VIOFIpF4kq4POFBDAR2NY=,tag:l9dVyCToPvyisY+TEoeoYg==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbk9DbXFkczV5K2lhOVBB
        V2wwZmR2SDBvL0RndjB2cXQ5M3IxazBPTUVBClZPWldyUTJod3hpeTd6VCtCbTF1
        UFRBT2NLVDFlT1lCYUdQeTFQM3pHMzgKLS0tIGtzTXNpYTliblBaUzlkMUhRNlRx
        RFdzd3Z4REJLeWFHOWY4OFFUalVMencKbXMn+gemHrlbSQUW67fe3vKgY3E/0DG6
        yl2CtXBXWHpHR9pn5QZa7wsEJDLP5yOLnwgbCFv1bZqGfeRjuBYCSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-17T04:27:18Z"
  mac: ENC[AES256_GCM,data:FwivjellMk6aNIJ1GLYcDVFU2CpLfLzr8nm2ptZtjKstK/xYH2Vys0uGgE6uWkWAJ5pNywstYujn6vjBLogHHl9KKzhYk83HXm7+0Qu2vP0QaYhsAjcTOKetIvsXmUrlmJJ6Uz2lOOBPiuSqKCLcZWSl/yAcvmGbI18xUrETLdQ=,iv:vRIXWOgVVOKlwo5uZt+89dbUy2ANyJRdBeNE4iRKFcU=,tag:kIdGj76RjMfYfKqQ081iGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.0
