---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keycloakx
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.0.1
  url: oci://ghcr.io/codecentric/helm-charts/keycloakx
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloakx
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: keycloakx
  install:
    disableHooks: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    disableHooks: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    replicas: 1

    command:
      - /opt/keycloak/bin/kc.sh
      - --verbose
      - start
      - --http-enabled=true
      - --http-port=8080
      - --hostname-strict=false
      - --hostname=https://auth.${SECRET_DOMAIN}/auth
      - --spi-events-listener-jboss-logging-success-level=info
      - --spi-events-listener-jboss-logging-error-level=warn

    extraEnv: |
      - name: JAVA_OPTS_APPEND
        value: >-
          -XX:+UseContainerSupport
          -XX:MaxRAMPercentage=50.0
          -Djava.awt.headless=true
          -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
      - name: KC_PROXY
        value: "edge"

    extraEnvFrom: |
      - secretRef:
          name: keycloak-secret

    dbchecker:
      enabled: true

    database:
      vendor: postgres
      hostname: postgres-16-rw.database.svc.cluster.local
      port: "5432"
      database: keycloak
      user: keycloak
      existingSecret: keycloak-secret

    extraInitContainers: |
      - name: initdb
        image: ghcr.io/home-operations/postgres-init:17.5
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 568
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        envFrom:
          - secretRef:
              name: keycloak-secret

    serviceMonitor:
      enabled: true
