# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:TNipu39lGkXilox9c2tRYRSYjdSrEVROCBkN5dBU6HI=,iv:KkoV5mnVvAl30q/d8J+Du8F3KSKm2V0SqrGrYrFKZt8=,tag:j4pcZknrw5K2WLr6uesVrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdXloYVlOam5SZVZ0Vjhh
            blUvMW9xc0NVcm9kL3dJcXRkKzIzN2h1TVJNCmRpYi9LKzJMamZKWU1KNzM5T1cv
            aFc5REhMeUVBeXRuSzBqS3RnVGh4bk0KLS0tIDh3QndQaDdTZEFoYTNHRWhkNUZS
            VXFOVXhPZ29oRmdZVzlZT3ZWTTBBeFkKwOzUnRTuwaSO2hJ+o+nhu6bgFKmNSxUt
            fAOjv7kjGnZcDUpO6eeRDpogl9BVJoe0DNDrueRUahIIeveze75Kpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T13:46:38Z"
    mac: ENC[AES256_GCM,data:LIzttKW6Hp5uucg7lfkb+FS8kW3ixTIPlPgpxB1NH5f6Rz02lHAZxsbrCGbhrhrnJa1msEAi49j4zSVviQUyhoKtTs606inUXiWaLr2C8cSuznoFdacYx/DJwReXREmxvRS4YfNNjtv0wLb1Vl+8O5lS9y1WKUfQTnYQOoz+Da8=,iv:KvM8r+hHJSafIGbypWootFieqRj2uLHW8rpu7Pla94I=,tag:KL2uDOFdGwOkCzuOReDZ8Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
