# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:/XH/rcdAMH1BBWq1UrQ=,iv:WyUbyazy6+TeYbsZn0QI2i3ew85lGB8AN9ax5hDqbaw=,tag:bNw0MNlmokTlX5krznO+Ng==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:2Bqa,iv:f7Zr2NIbNItdoFNY/u68TIAL4P0QD9GIs00U2LMuYj4=,tag:d9KEgAK6cR0/B49aVckESw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:CY5e6Nv3NRTC1pKqqUyablNi/Uy1LA==,iv:9GZTPhG+jaLlIv6e3jcoxFfGypD6F9xDnHFVoRb1ZyU=,tag:600w9IdDoSat4JCEbU3Jmw==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:lYJ7yQ+V8GaZjgE=,iv:VB9XhViD86fPnBC0z2pHSdNAhNKLRR7tHIBz6CQqMeo=,tag:M68KhSywr8SKcl88khf+mw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:DFuwYqBPqq3r6mWkOPpXEM2xpA==,iv:4rCsbFcObtkks22NZvwXdPPvZjQdq6SyDUgS1iBtAxI=,tag:b94EFVeyJ8mLZnPQR27q3A==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:4aRWzfIj1miXYga5e39eK+M0jQ==,iv:IYOlyy+84KfOxAAA3hMLclozyvfohijHPk+rKNJoE6Y=,tag:2PC5dIsbnK88eTift8nUuQ==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:3DrpRjBpFTr9dI/dLNxlqn5auXv4zxMUmtmrlvApw7PDUFvoAyCMQpY3aZCfD1vkBnXuzZoPk/ATpu3rvjXk4+WP4PGCjL0DHIzx/XJMpc1ZyfC6rwo5iTGr/XnIXPjL2p+RqvbS8jY4z5L/KA3ARiN50ep+z26lW7vXdEOyuwFUJA5nk541h+AWsg==,iv:Y8xoVPHARxw2JYLvXK1s7+ocVE5BrmDcG2iL4b35YNU=,tag:VRVlOG7/micAWe3hnYWSyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYzJLY2NtWS9QaWxjTmRa
            NkJGVTN6ZFRYQ0twWjdZWjJlbmd0YlJoNmtzCjhQb2pmSDh2czFjUENqSVY5NzE4
            S2ttSmpDL2s3ZTg1L1NtdVpzZkx1M3MKLS0tIE9tMnpNV2lPeXR2S1VibVRHR0ZS
            cXNxL2JENVpGcW9VaVJ0anBSdWFHb2cKSmMQCei/Ghg4k8GUSq36JUfaFgr2ZEgQ
            3EEP2X/nxmN8SoGxPxO9KNRjMOCzMUSP3pH+qOPspDbQ8p+w/g879w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T13:23:12Z"
    mac: ENC[AES256_GCM,data:2NJUbkxgGeoPfBhFMWzDomvAWaRz5WIWMaFjLMY11bcReyWidlCEIryYFFtejO53Rt5UhE54IoXuHmIlHI6HSkJlm55fHnI2n592ZgpBPuMG+TsOdxsZztYdBbXqw1vei8YmxbQvh+0jOa+hf8J7MQEoyfPQSOsbGxXopUu0YoI=,iv:Mg5NFcAvOgQBlTa8kTqEKIVeJc1J4ug0/E2HSlnTeoI=,tag:vHx7LeoOMtdD16M2YPCpYw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
