---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.23.2
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  verify:
    provider: cosign
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
  maxHistory: 3
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    crds:
      create: true
    resources:
      requests:
        cpu: 15m
      limits:
        memory: 1Gi
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
