---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
  interval: 1h
  values:
    crds:
      create: true
    resources:
      requests:
        cpu: 15m
        memory: 128Mi
      limits:
        memory: 512Mi
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
