# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-objectstore
  labels:
    cnpg.io/reload: "true"
stringData:
  S3_POSTGRES_STORAGE: ENC[AES256_GCM,data:pEa+lRMPPqLP1pzsO0QLtaG0k5Xn5AyhsM1GjILE4BsN7naipNcL1gjPC77iAILs8OVZc5S/mUkorjqEBJbvjz8=,iv:uB5/srF+nTa37cVr2qKExXozxKiyz/8FnR2Se0P+EJI=,tag:yDRfj7sWkHuJq4I/4KetvQ==,type:str]
  S3_POSTGRES_BUCKET: ENC[AES256_GCM,data:Ns6hsPsnT6I=,iv:nyKfi8/LPITjnr+3jubrZQKsDktVVr6BdtJkHLn6s7Y=,tag:kEKrUlTREUXCwxf5lAIHfQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZpNeHKpMpAWGV9C+LIgKwNVErGafJ6YrOPOQ07ovUVw=,iv:H56raz6PAtqyGRFyFAjNEKvjGVBohGy6WI7a20g0Ado=,tag:fl3YIMLA3Sg8c6Si4bojxA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RMPi8QGvQg7Iio7nWXwE8fCY+ZYI+jABW6kGFBuYMXFX+uYlNMilg/6/J3MFdG812LaUE0pjIRQP1YgArq7KfQ==,iv:+zvgpJvS3PYhH5WFSJ/YuRfsBWU6ha1lE5nQws9vkXk=,tag:QT5I7vFFrLR1BMyN061LVQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcW5CMno3U0tTOFp0ZW9l
        bmt6UEFzZE1CQWpMUll0VmpEZlk0SVA4eG5JClhJVjErSXRsSFh6VU5KckpIN2M4
        ZUROUnUrSllzZDdXOU5OdWt6akZlM3MKLS0tIElVWFUyd3U1cDE1aSswMHBMZ2VR
        dVpnM3doUTgzNzdNdUZnSGU2Q0pvaEUKRzgSFt/WxQhTrYdRTgLYvve0PKo9aP/D
        hOJ0IJre2uwaLFLHTWir2sMf3XSyjQHDjGS/naALLG8E1pAFJybD4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T17:46:24Z"
  mac: ENC[AES256_GCM,data:zhRbpNBr9h+IaosqKbUI519thYXcuacCn8Q9z+j0WvlrKN99CIP/eZLiP3t2Zv0ePN/gvIXU1noMmXTZuQTGefV4Ruhw/SlG83n3HzAKHop6nF95N1DY0PpqcG0an/jiu9Gcgz5NVjOiZ4gV2tyV7gU/zltelaTsXK9U//fYK7c=,iv:MlFWCqXJteA9yTfeGCqp7WXQZlZBkR5wCDRLUoJfD5Y=,tag:l3ouZWP5WdSM+E5RkCNDbg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
