# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:T9V/J77fm5oGag==,iv:nI9gaEtvmhtJMIB4lVG5fFK4gTY/QCKSlPE5Hw4vsWM=,tag:WhPPC3P/9jzkE4yQwOrLag==,type:str]
    admin-password: ENC[AES256_GCM,data:bmH5XINwpXPNN9c=,iv:2B4s3/GyzdeZqeXBd5uGsdmDJe4pln6oBMl0e8P2hMo=,tag:XB0bI21ZExeDFIjWpzIVVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMTNDTkduYVhwZlEwOWZv
            UFFOK0hMREhXMXBXTCtWMWhtd0VVTGhiNmdFCmxqa2hoak4xVVVOMUVINlpnaEtX
            U05mS1hOUGlCMVV0cXR4L29xVGZHWGcKLS0tIDY5T203NjFJanVaVzlMejRVRHE1
            U25hVGRvQXNlVXhIOUlBSzBFVXNiNU0KuyTG4YXk6tzeR+yc7qZ2D7Ef3Pn5wcDN
            e6mRXFV/5jfz9SifdIYCluiW7t2VmEeoipjYik8vC7+ODDNAdY6bQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T21:23:10Z"
    mac: ENC[AES256_GCM,data:69zL1WAVx/R5xEFNHwTfiMlI7rx8pmkNYOG50ygwluDgp0Aej0d9uQzYikv2XFvYuLLeQ4T2hMmZlbxFuFJgWY0NNebwj7C7m8fo7lmCZ1y8KlXbsYQzIrlIJ1Z/cyWBA1R1KDfI0o+PTQCAPz6+iisyMCaFARBvzs5qmtBCthI=,iv:mfPyECWItAzDWR8XXq2kPLVJlYwaN1YqDwNbIgkSkB8=,tag:ySbdLFopCymz5TNIJWvq5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
