---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  "*-ks-all":
    desc: Suspend or resume all Flux Kustomizations
    vars:
      STATE: '{{index .MATCH 0}}'
      NAMESPACES:
        sh: kubectl get ns --no-headers -o custom-columns='NAME:.metadata.name'
    preconditions:
      - '[[ "{{.STATE}}" == "suspend" || "{{.STATE}}" == "resume" ]]'
      - which flux kubectl
    cmds:
      - for:
          var: NAMESPACES
        cmd: flux {{.STATE}} ks -n "{{.ITEM}}" --all
