---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: download
# components:
#   - ../../flux/components/common
resources:
  - ./namespace.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-anime/ks.yaml
  - ./bazarr/ks.yaml
  - ./bazarr-anime/ks.yaml
  - ./recyclarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./aria2/ks.yaml
  - ./spoofdpi/ks.yaml
