---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wallos
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      wallos:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/ellite/wallos
              tag: 3.3.0
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 25Mi
              limits:
                memory: 100Mi

    service:
      app:
        controller: wallos
        ports:
          http:
            port: 80

    route:
      app:
        parentRefs:
          - name: external-gateway-cilium
            namespace: network
        hostnames:
          - "{{ .Release.Name }}.tuilakhanh.id.vn"
        rules:
          - backendRefs:
              - identifier: app
                port: 80

    persistence:
      config:
        existingClaim: wallos
        globalMounts:
          - path: /var/www/html/db
            subPath: db
          - path: /var/www/html/images/uploads/logos
            subPath: logos
