---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
  storageClassName: openebs-hostpath
