---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: snapshot-controller
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    controller:
      serviceMonitor:
        create: true
