---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-config
  labels:
    app.kubernetes.io/name: recyclarr
    app.kubernetes.io/instance: recyclarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: openebs-hostpath
