# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
stringData:
    CF_ZONE_ID: ENC[AES256_GCM,data:gglgptgW2AKWG46j3qbjeUkvG6lCgJqZNhZ2uLISzbE=,iv:0JPuIQXODaarrfrsj+46t9/szZC8TznrmPXuLPNckPU=,tag:yoshcIQxbA/gQxsuHtNTLg==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:6l1iQJa+GzO3GPCxFFRsc/1lX3YheGZYQyXCF3NAjMsgijLS3T6x7w==,iv:rtQzlyhu+dJfZhA0FPHiWz+vqIDPycVUocygHzVVT/E=,tag:yHpXHb6iWCZiWZkDATul/w==,type:str]
sops:
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN1dEWkluYTBWNlVBQmR0
            bnVveGVPY1lRaXlYYVg5VjhsNk43RUhKSjJZCkdFdTBrZWp1NmxJQVN4YWFiWXBU
            VDN1K3ZMWmxQZU1xaWRwbWQrTnFLWWMKLS0tIDAyWXVxazJxYWJOR2UwYjU4TG1K
            ZXVrVWErN3p5NWdub0tJQTRXK3FNZXcKSpXF8YCJwFfQKxM5aUQHB+Jzf8H3d+OT
            0shOWDICXpo8iS2gCH3k3TEXWII+3wxroJR+q3HeGMRmCAaC4nVETw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T04:19:09Z"
    mac: ENC[AES256_GCM,data:KBOMv4SWLFfhjJS+hsovMOdKUYQ/q5rRZubI0O9buQ/X6jdfw1CIKfDTdKi7Kno+kwrKF3lHWBIQTmSedbcBStLX9quEscrFksT3alC7YUPvRqTXO3O5l7PhhKi3yc43BxJJ+J1L60vjzhtragiRaXQMJj3/jWM4QOTv14EL4qY=,iv:dXEb/neGNpp10kD6TK/lgQgR1Ou9/uJK6gENYmBxGZU=,tag:pcTOzNasi6idgCkcuXKPLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
