---
bpf:
  masquerade: true
  # Ref: https://github.com/siderolabs/talos/issues/10002
  hostLegacyRouting: true
cni:
  # Required for pairing with Multus CNI
  exclusive: false
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
# NOTE: devices might need to be set if you have more than one active NIC on your hosts
# devices: br0
endpointRoutes:
  enabled: true
envoy:
  enabled: false
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: false
dashboards:
  enabled: true
hubble:
  enabled: false
ipam:
  mode: kubernetes
externalIPs:
  enabled: true
l7Proxy: true
gatewayAPI:
  enabled: true
autoDirectNodeRoutes: true
routingMode: native
ipv4NativeRoutingCIDR: "10.69.0.0/16"
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: "dsr"
localRedirectPolicy: true
operator:
  replicas: 1
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
rollOutCiliumPods: true
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
socketLB:
  hostNamespaceOnly: true
