---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: alertmanager
  values:
    controllers:
      alertmanager:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: storage
              accessMode: ReadWriteOnce
              size: 50Mi
              storageClass: openebs-hostpath
              globalMounts:
                - path: /alertmanager

        containers:
          alertmanager:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.28.1
            ports:
              - name: http
                containerPort: &port 9093
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 99M

    service:
      app:
        controller: alertmanager
        ports:
          http:
            port: *port

    route:
      app:
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - "{{ Release.Name }}.tuilakhanh.id.vn"
        rules:
          - backendRefs:
              - name: app
                port: *port

    persistence:
      config:
        type: configMap
        name: alertmanager
        globalMounts:
          - path: /etc/alertmanager
      secrets:
        type: secret
        name: alertmanager-secret
        globalMounts:
          - path: /etc/secrets
