# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:9vWk7eu7cEbcoaAR8uBvh+daus7mKNeD0Qp7pUtfhSI=,iv:jPNoZ0CdAUiVhTm4MRUZXMenjSNHhVRLf5hl6/ewSF0=,tag:jGZWSQkcrDIN8kIFi8Z9+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUzJJdVZxTElhMVk3N1BN
            V1ovVW80cXlqdEdpYzhTWktDdDMzOVN2aHpBCjIzSk1OTVAxa0JyVGpmQmdFS2c2
            aEY1QnFKeklUdktJeXF0Mmg1WmhpMkUKLS0tIFFJLzRGZ2VLYlZJSWQzd1E5ZFM1
            YjZWaUI2d2pkcDROcnJwY1h1a1JuL00KlI+5a6NeGtyCKZG5vDPSUMSiEY4ld7Wt
            qUDaahmakqCGIgatPZkIkT28lrjbl+FbbS+1HR7Lzg2iDKlLkcqqRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T13:57:27Z"
    mac: ENC[AES256_GCM,data:8le7/3KT6xlh3PvWc5G0Kjof80uZuTEkdVQMTSN7YURdOmgg5PwTcMIeYMq3XkAyS5p1j9G6nm4RrnVJufLRaIzilN1tJ19Zq6LrnRkcpCxYCuxoh4Oz+2VLQxaaMb3kwNbgVk14Q72uV/BU9nVUNrDRZ0iOZyxWFCuRSf0GFSE=,iv:FpjTxSW02BT8zQYpNA3N+QM3VC7sq+6uDweE5MznzN0=,tag:bVXgSqi2A7EbSjzvhIpNXA==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
