---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cyberchef
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cyberchef
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/nginx/nginx-unprivileged
              tag: stable-alpine
              pullPolicy: Always
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: { drop: [ALL] }
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }

    persistence:
      cyberchef:
        type: image
        image: ghcr.io/gchq/cyberchef:11.4.0@sha256:379c6cbcfd8cc10b8e045548f3ebaa82ce429e4b40cf60e4532e116a4c67884d
        globalMounts:
          - path: /usr/share/nginx/html
            subPath: usr/share/nginx/html
      tmp:
        type: emptyDir

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        parentRefs:
          - name: envoy-external
            namespace: network
        hostnames:
          - "{{ .Release.Name }}.tuilakhanh.id.vn"
        rules:
          - backendRefs:
              - identifier: app
                port: 8080
