---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app aria2-ng
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      aria2-ng:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542 # gladius:external-services
        containers:
          app:
            nameOverride: *app
            image:
              repository: hurlenko/aria2-ariang
              tag: "1.3.10"
            env:
              PUID: 568
              GUID: 568
              ARIA2RPCPORTT: 443
              BASIC_AUTH_USERNAME: ${ARIA2_USER}
              BASIC_AUTH_PASSWORD: ${ARIA2_PASSWORD}
              RPC_SECRET: ${RPC_SECRET}
            envFrom:
              - secretRef:
                  name: aria2-ng-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 150m
                memory: 1024Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: true
              seccompProfile: {type: RuntimeDefault}
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
                  - FOWNER
                  - NET_BIND_SERVICE

    service:
      aria2-ng:
        controller: *app
        ports:
          http:
            port: 80

    route:
      internal:
        parentRefs:
          - name: internal-gateway-cilium
            namespace: network
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        rules:
          -  backendRefs:
              - name: aria2-ng
                port: 80

    persistence:
      config:
        enabled: true
        existingClaim: aria2-ng-config
        globalMounts:
          - path: /aria2/conf
            subPath: config
      media:
        type: hostPath
        hostPath: "/mnt/disk/"
        globalMounts:
          - path: /aria2/data
            subPath: downloads/aria2-ng

