---
# yaml-language-server: $schema=https://schemas.tholinka.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cert-manager-csi-driver