---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wallos
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      wallos:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/ellite/wallos
              tag: 2.48.1
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 25Mi
              limits:
                memory: 100Mi

    service:
      app:
        controller: wallos
        ports:
          http:
            port: 80

    route:
      external:
        parentRefs:
          - name: external-gateway-cloudflare
            namespace: network
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        rules:
          - backendRefs:
            - identifier: app
              port: 80
      internal:
        parentRefs:
          - name: internal-gateway-cilium
            namespace: network
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        rules:
          -  backendRefs:
              - identifier: app
                port: 80

    persistence:
      config:
        existingClaim: wallos
        globalMounts:
          - path: /var/www/html/db
            subPath: db
          - path: /var/www/html/images/uploads/logos
            subPath: logos
