---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    controllers:
      server:
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: immich-gpu
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              # renovate: datasource=github-releases depName=immich-app/immich
              tag: v3.1.0@sha256:079cc990b26a88d71f96027341c67329cb11829d4c341ce33b3718fe0f84cbfa
            env: 
              IMMICH_LOG_LEVEL: log
              REDIS_HOSTNAME: "immich-valkey.media.svc.cluster.local"
              IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning.media.svc.cluster.local:3003"
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: '{{ .Release.Name }}-postgres'
                    key: url
              DB_DATABASE_NAME: "immich"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: &port 2283
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 4096Mi
            securityContext: &contSec
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

      machine-learning:
        type: statefulset
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: immich-gpu
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v3.1.0-openvino@sha256:627dfaf9339037be132209784883f7be13c1deb6be799454797bf6f231331f5b
            env:
              MACHINE_LEARNING_HTTP_KEEPALIVE_TIMEOUT_S: "0"
              HF_HOME: /cache/hf
              MACHINE_LEARNING_CACHE_FOLDER: /cache
              TRANSFORMERS_CACHE: /cache
              HF_XET_CACHE: /cache/huggingface-xet
              MPLCONFIGDIR: /cache/matplotlib-config
            probes:
              liveness: &mlprobes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &mlport 3003
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  timeoutSeconds: 1
                  failureThreshold: 10
              readiness: *mlprobes
              startup: *mlprobes
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 6Gi
            securityContext: *contSec
        statefulset:
          volumeClaimTemplates:
            - name: cache
              storageClass: miroir-local
              accessMode: ReadWriteOnce
              size: 10Gi
              advancedMounts:
                app:
                  - path: /cache

      valkey:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.1.2
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 200Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - "valkey-cli ping | grep PONG"
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup: *probes
            securityContext: *contSec
        statefulset:
          volumeClaimTemplates:
            - name: valkey
              storageClass: miroir-local
              accessMode: ReadWriteOnce
              size: 1Gi
              advancedMounts:
                app:
                  - path: /data

    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      server:
        controller: server
        ports:
          http:
            port: *port
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: *mlport
      valkey:
        controller: valkey
        ports:
          http:
            port: 6379

    route:
      app:
        parentRefs:
          - name: envoy-external
            namespace: network
        hostnames:
          - "{{ .Release.Name }}.tuilakhanh.id.vn"
        rules:
          - backendRefs:
              - identifier: server
                port: 2283

    persistence:
      photo:
        type: nfs
        server: 192.168.1.36
        path: /mnt/disk/immich_data
        advancedMounts:
          server:
            app:
              - path: /usr/src/app/upload

      tmpfs:
        type: emptyDir
        advancedMounts:
          server:
            app:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers
      
      tmp:
        type: emptyDir
