---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/trust.cert-manager.io/bundle_v1alpha1.json
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: postgres-client-root-ca
spec:
  sources:
    - secret:
        name: postgres-client-ca
        key: tls.crt
    - secret:
        name: cluster-ca-cert
        key: tls.crt
  target:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: database
    secret:
      key: ca.crt
      metadata:
        labels:
          cnpg.io/reload: ""
