---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria2-config
  labels:
    app.kubernetes.io/name: aria2
    app.kubernetes.io/instance: aria2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: openebs-hostpath
