---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
spec:
  components:
    - ../../../../components/gpu
    - ../../../../components/cnpg/app-template
    - ../../../../components/zeroscaler
  dependsOn:
    - name: kopiur
      namespace: kopiur-system
    - name: postgres-cluster
      namespace: database
  interval: 30m
  path: ./kubernetes/apps/media/immich/app
  postBuild:
    substitute:
      APP: immich
      ZEROSCALER_TARGET: immich-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 10m
  wait: false
