server:
  port: 8080
  externalUrl: https://share.${SECRET_DOMAIN}
  internalUrl: http://filebrowser.media.svc.cluster.local:8080
  cacheDir: /cache
  database: /home/filebrowser/database/filebrowser.db
  sources:
    - name: GSGA
      path: /mnt/GSGA
auth:
  methods:
    noauth: false
    password:
      enabled: true
      signup: false
