---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
spec:
  targetNamespace: network
  interval: 1h
  path: "./kubernetes/apps/network/cloudflared/app"
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cloudflare-tunnel-id-secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
