apiVersion: v1
kind: Secret
metadata:
    name: copyparty-secret
stringData:
    config.conf: ENC[AES256_GCM,data:dNTce71KaKgSVsldwBN1dJfQpZZmbwQJ5z4fJ19QE7xSiuEhWzdtz4WmGWL5LF85G61udBIkQW3n3J99SJ7atfihTyL5XevCA0jFsufjZ5XwiKVHrhay9t8FlqMEML+b4d/GiGYyI7aR/YmRal52CFWFFhD8+SrSkFmRetuJ3zOQMd1pWoaAJZHw8eUqJCE4LFiTxsasboeBW1/0sxrhFpbTeQg1w37KSaQQ0qGGgFaV7wWEgw83tPJYxSVP9PjUuwRS7IPBb9FgHc+I2biCPea5GX9Y6+s5YAgi1MEq6jvrG9cMijz8LxvraBPrCIoMnli+Gnlt9AkJ8lUFr6uTzDH8S1Fyfk0pXZOwOvtNQEKEe+OK32OcRdp9nrtTyj8bE6jtqY4A7bM27gSo/TtMP9lFLOT/L4mnDw==,iv:Po9P3eCJwc2fxnj+oGE12Mcw2N1T+sIYDguABzV+Wow=,tag:llFVq0jGfAEUqLkLnVm1YQ==,type:str]
sops:
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bWVBV3VCUWRJaUttSGdT
            WDc4UkpsRWQxMU5iQmQ3WjNwVTJwRCtIZVFjClpPK2NFZDhLOWJrbUx3VmZYTHpk
            ZWs4Vkk3Q0dZNjN1WVVESUluelZNZWMKLS0tIGlSTU5yclM4cjJweXdTSlArQTdD
            K1VuLy9rWlpzb3NFNzJQWUNpaHhPaHMKt9Vi1b16jwPNS12LooENKYlG3VPPJ1fH
            BrFamzg7T/P2mmL+oXB9yFuWTuxqrQqioMbPzZ5/QgB8GFQQfNm8vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-24T15:44:29Z"
    mac: ENC[AES256_GCM,data:XS2mjF5g/ZEOAWUG8/I5pRP/W9FS3hppk3Ka5Gnch/Kd1y9bMFBcStTWuPOHBhhZQZjFyvuWT+iqVQjm1AJxOzrWs9bjljf6bXmrZi6MliunIUWz0Wunffq528JMlOcw+uM6e/RiVggdsNAyn0KQdaagi1JPwSKzn8Exlqe0Ovk=,iv:kCGxr5IvJ7oVwMpNVSmRDKhPgRnEeUxnn66h1wWDeVM=,tag:ILpQH/3ubYX2+T1fpYwa/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
