apiVersion: v1
kind: Secret
metadata:
    name: copyparty-secret
stringData:
    config.conf: ENC[AES256_GCM,data:WwZSvCAEshl5JRuqEEU6UfPTLUjf/Ss7MCWe1KSpnUXvCZddiHp9ePq1VsFwn7LdcwS4EVjsnfbGGKCuAs3MZODTChNC2JxLR8CAkTi9hLZV1SEiBtWh3Vg+Fu3FvWPV5pzsw3wWoxfUyrboVLqxg7QbT/alXZUuThL1eqC6QVqDowl4c6auNjVrrwOGfL7ZIGPnNt7IpO7N97fDcbn+nqNnZKn8xDItw0VRqekxQjBI2+Y5IezFG+iRi2YachMq5vkRsF6upJB4Mj0Wp1xCKGkjlMBSiIAgZxxqWhPnXa8GkaCm5Pq6UH16B8pp6EBMWhAJ7V3PbxWPlBJn9qwXh2pmk4uHxUVrW5jIV+maPSpHU5emuHpDq+efvFW3O64KzS8dEKCl+r/dYYaLn9/znyyd04kXev886q8XtvtwLjOzpOtQ9Bm7SGTjOeR14iQHPvrwDqB1q4aVhCFKbMwwb+sZcHxanBOlPIjG5PEb+E0NDe4WQl0h5L34nfTbXCm/,iv:kjmMAOyVjBYz67UyuqS9he0CkMFj7MGUjSXUlQoBs1k=,tag:db2ApNEu79Ay5kePcPoRsw==,type:str]
sops:
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bWVBV3VCUWRJaUttSGdT
            WDc4UkpsRWQxMU5iQmQ3WjNwVTJwRCtIZVFjClpPK2NFZDhLOWJrbUx3VmZYTHpk
            ZWs4Vkk3Q0dZNjN1WVVESUluelZNZWMKLS0tIGlSTU5yclM4cjJweXdTSlArQTdD
            K1VuLy9rWlpzb3NFNzJQWUNpaHhPaHMKt9Vi1b16jwPNS12LooENKYlG3VPPJ1fH
            BrFamzg7T/P2mmL+oXB9yFuWTuxqrQqioMbPzZ5/QgB8GFQQfNm8vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-24T16:15:15Z"
    mac: ENC[AES256_GCM,data:0a/cNf/9RttLFUXo86tlpE4+gJ7TilPjRQuR8pjktk9rqzXfZ3OVFcJ2iZEf1KlpaWRAtRsJSlx3Cd3sUTrmSx7RlKpORRCf/FvwQqSd0IjHmGsv4Dmxaqh19/s9FIyfk4vOsMxgqKrdNlUlhEDQpySfYLEk5ubAmtIREg5bnLU=,iv:nM5GZJOgZzGxMhFBGIyA2s4nHtyhaAWvKrNacyKelPs=,tag:IykiB1Cv5rOf/xi6qAzfUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
