---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app

    image:
      registry: quay.io

    serviceMonitor:
      enabled: true
      relabelings:
        - action: labeldrop
          regex: (pod)
        - action: replace
          regex: (.*)
          replacement: $1.tuilakhanh.internal
          sourceLabels:
            - __meta_kubernetes_endpoint_node_name
          targetLabel: instance

    prometheusRules:
      enabled: false
