---
receivers:
  - name: "null"
  - name: "discord"
    discord_configs:
    - webhook_url_file: /etc/secrets/webhook
      title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
      message: |-
        {{- range .Alerts }}
        {{- /*  Severity  */ -}}
        {{- if ne .Labels.severity "" }}
        **Severity:** <i>{{ .Labels.severity }}</i>
        {{- else }}
        **Severity:** <i>N/A</i>
        {{- end }}

        {{- /*  Description, Summary, or Message (choosing the first available)  */ -}}
        {{- if ne .Annotations.description "" }}

        **Description:** <i>{{ .Annotations.description }}</i>
        {{- else if ne .Annotations.summary "" }}

        **Summary:** <i>{{ .Annotations.summary }}</i>
        {{- else if ne .Annotations.message "" }}

        **Message:** <i>{{ .Annotations.message }}</i>
        {{- else }}

        **Description:** <i>N/A</i>
        {{- end }}

        {{- /*  Details (Labels)  */ -}}
        {{- if gt (len .Labels.SortedPairs) 0 }}

        **Details:**
          {{- range .Labels.SortedPairs }}
            • **{{ .Name }}:** <i>{{ .Value }}</i>
          {{- end }}
        {{- end }}
        ---
        {{- end }}
      http_config:
        follow_redirects: true #Generally a good setting for webhooks

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6h
  receiver: "discord"
  routes:
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
    - receiver: "discord"
      matchers:
        - severity = critical
      continue: true

inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ["alertname", "namespace"]
