# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
stringData:
  token: ENC[AES256_GCM,data:Za03IkHRSft+vj7yTb4KK/2wvoJnE+shdJF4OU6Q9zxWe9dhMDHH6Q==,iv:NbMF4t751glM1p8D5MzLbVVLu0To7ljWbvdqcA4SXaE=,tag:2hn3jvW07jFfrU+k/QGuVw==,type:str]
  uuid: ENC[AES256_GCM,data:5FFUB7M64tOg7dRA+gFwmeItPejSf9Bka6KAXGEVBCGXv0it,iv:PPNUv/+s2caHtLAXl1bqSIkx6ofN15e+9Tb/fy9PQow=,tag:249v7QYnvRk5hhdRWkcyCA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreFFhbWJ5ZG02VlVhTUVF
        U1VhTFNQSGRRSFVZeCsvTkV3R3dJa0VacDBNCnZxb2l0bWZWUVJXSlR4dkR6cWwr
        RUJNV05WWDV2UXJvcDNhRElOSWpnUTQKLS0tIHVlaEFkTG1xZnBmSFEyaTJjM25C
        NkJuZ2NWMkM3K2h1MnJQQmt2ZUNVNTQKDa/HKWYsThW8YxZykfS0POSnmxb/YYRO
        pYNTOIyEVnaZxupME+qgk6lIcidLm+9f7SqSF+opWQSizDRNALuNSg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-08T12:57:07Z"
  mac: ENC[AES256_GCM,data:n+hm1P/zgeC7t6kXGSpiX3MXClBc1BKDjfXijRA8aqx/sozXx2Qux+ybS0D4uOUiViuXchWjT/QH3YpvbGOp17TiVb5/4B/sHxPUkfdqRKuGxH3lUdoB13YNrLEhhMl5m6qLS9422BCELnKVF1s/wYMtjglKGe5Ii2mH6tCNIuU=,iv:LgnthEpNyfwDqgqyy8ERHwKifbTisyLnj4w50hHMKyY=,tag:bNVHqbgBE+vUZPTF1QZsnw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
