# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: volsync-s3-maintenance
stringData:
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:kIVmsoue5t9J3e5SfLeqCj8=,iv:88fw+SBvHWU1Ei8ZHIT5t72OqbEIbmjGyFpUzBJec6E=,tag:7QS10+MEjjQ4Uicwu1hMzg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:Fa9K4SbEGqZFI1S/uTbQHg==,iv:Xoa6POwKqLTrzEM2b8JfVyhnyz/ymvU6fkG3wUQZ4i0=,tag:ajoJSw4eyZ2oiDdHb9fmoA==,type:str]
  AWS_S3_ENDPOINT: ENC[AES256_GCM,data:pTCeWMP32E2K6o1c82Q+kRe2uPzt8YYYtDvXATWyKNP/v/Ai/NFQn4PWJhNMOeXWKiFsj884Ixd3,iv:nhZ00F5274jlxgNJPfD2lW2VS4g21ZSt+QPU4ISeLxE=,tag:1id1YOj3NA1mwmJ+tVKZdw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XL93EknP2hOzLxjWJYBZ0fCd2riljZrg6wJ8B3hEKms=,iv:qxO0TmZcSQt8ZqjpOXz5FJOy3dwt8XVUx8e7GvD6YZM=,tag:xcaP5NhpodRVUu3YNpFfHA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:USZxmAj1qUIJxINvYPGccTSHK5WW2VLFflhrNteaTvcwXCtqqdk3EWM+d75KiTck1aFqDJHlh5alpA9IMf2veg==,iv:IGu7PQkCVekss6xxThW8jHQuocmjDjCevaCoWuIc2WU=,tag:lArT52UpjvoWxcGrCgnW7g==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNk1jM2lZZis4Y3hJMGVs
        aEhkT3laaXNsM1BNUUI5bnZpNVl2QnBaVmhRCmxWRi8zaTIxMFlEaUVnblQ0WllF
        Yk5Gem9RSXlROHRWNVo0aDJNQVVnWFEKLS0tIFRmdVh1ckduTXA1bkliYlA3cTZP
        ZzE1MGYyV3VCMUQ0WTc3YWZEMXl4cjgKFI2d4brqDxFKKAGhRSHN/26G4qO+QDud
        l42Y5wcvoIKmPMP461ClA/jbH9L4iPzUO8bhUnJbnuU984b+U/3KDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T19:33:23Z"
  mac: ENC[AES256_GCM,data:Yx5Ba3hAqISrBwk3+lTWWKe5EEjBlwTP1/mTaPEZTJtthXgKimhcTxp+9kTHlWkiEVKYC5AHeYmT7X8NPVCclLyIk0JCT6Owi5CCBSn13b5pPh78EzmrCJ5QCSrWeTtUSQcKotiYsr2MkxwXWjPt41C4HM6kMlGb9MHqMkO3bxY=,iv:A++bMUvey1nYJc8jqAKJstrZjwFrs4+S70cedc3em4U=,tag:GTVIHhxLYhhkoMfqTTnr/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.0
