# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  webhook: ENC[AES256_GCM,data:kTDSqqJgqmWi19V7XtFvxMvxCyX2EML7KSfIanY5+wRcTF4GHYhk5Za1Z/4BOEeR7PcAoEjcE2EnaOCIhsnU8k8Cbrcm5+2FVE3+EjH1WeiieI8sA05Y0xETnYJx+SXlJpXwZGYG6Teea6uUVoDrVY9xHC4LP+jhJQ==,iv:xoKZP6wetXqMmyiaD++uYlrVOBA9/zcRqqDlqBvT0JA=,tag:Wsx6SehLMh8ebIZo47nd8A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcVRmVmJ5MWdCS0lwUXQr
        MFVmcldZZzJhRy9INEJKZE41ZDhmZ01ycVdZCmRua1JsRVZuR0JmY1ltODBxVDQx
        UTI3enlQbHNzS2htRTJqYVA3U0x4Y1UKLS0tIHdvUytPV1FoWlJpTnRWSFp6SHpD
        NWRLVXNOQTNoejhuZnY3NmhUa1RWd0EKFOqOxTMzcNKhiEN8E35cyHwQFAhNBhgI
        irZTWz86lphGsSVzTym1MFit7cHUQVlsAl8nWdPkScwtql0HZsmukw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-05T03:58:39Z"
  mac: ENC[AES256_GCM,data:9DxZuyjHPDtfX04szpiETgKq4b7qYkRwzJj+aWN7vAuwwylfbSXvI7G2iKBfg/mQ3QWYrKLF4/vmzEV3bhUZ0w6PADSVfqLPU9GLuKLUvtydH03l7pazX2rrtG+hcpUgOwjcO1lB/wPZKVk7b0m3Vxe4ac5ZX7TrecQcmrNYbA4=,iv:aRPGxXKNCfeLp7ZcaSIvVYINW5oiYm7CyiBv1S+ZgtI=,tag:Th14HzmIhiuOi1Y0IBWb2g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
