# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:OlJSKEkZS1T0SCB8njMkb1Z/Y26EDJ4PKsnhKf8WTzw=,iv:P4BpFSynx+0ewQm10QTzrNyn5xmgR2ZKoAaSc/yvNyU=,tag:PTvixlFng412mdMqWTKEAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQi9GcGZpbFlra2tzSWtK
            RnpWWXJ5NURpVXE1bHQrT2locy96RGpFNEIwCmFtT0RaZWw0Nll2MTN0WTN1OWVE
            RGN1OVlBNW5hQURmTHpseFBxQ0hrQXcKLS0tIDJjOEtqaTkzbmFiVkJHbHk3RGE5
            MzJMbU1jN3d2djhKdFVjcTRGSTJEbjQKRnUWIggnGyZ9g6TQ4LpIvtwjKCxTQCo2
            pgSVDQPtLxVnZNapgy3ciEXZ3pd5f5efdPKySx1kOz9BJ2s69U6Mfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T18:24:38Z"
    mac: ENC[AES256_GCM,data:X6WxZ0qezeK0t1L83A65vaSifbaMe8dQ/5z6CxyNpFPHkMlHrOxoZzLEQ6rxxKT/TybR9YBDBGfPWVXgXv4zr3+bfwOnPgS+A6G7V90vRuH+NATMEF8Gp0B1NyFUKSai8W+6SLlhNM4KPZWT0pnzRiC9awKGIvXPZwGuVEAU4D8=,iv:cMquH3i8/cOQcSlmRnO/Cm6mpD4X3AYqvZl/rp5f+/A=,tag:722utTEWV2rbl+7OWkhsDg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
