---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugin-gpu
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: intel-device-plugins-gpu
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    name: i915
    nodeFeatureRule: false
    sharedDevNum: 4
    resourceManager: false
    enableMonitoring: false
    allocationPolicy: "none"
