apiVersion: v1
kind: Secret
metadata:
  name: cs-agent
stringData:
  SRCDS_TOKEN: ""
  CS2_RCONPW: ENC[AES256_GCM,data:ahXpfYPpke23H35OrWxb5A==,iv:3g35hhT4DrV6+foE6qbRYArZ2fl7LXDmcpxAyB6LNyk=,tag:yxezjqUw8u9JpqNgTvF69w==,type:str]
  CS2_PW: ENC[AES256_GCM,data:00gHf4CAzArn,iv:CmmB8h4FLA38ZDVn3EcHHCgirGwOZjtD8VpzFDdiLUA=,tag:Jbc0/QFyz68u2/NqvXLJZQ==,type:str]
  WPWEB_STEAM_API_KEY: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBR2JleWRTNnhpSitBVkQy
        YWlZcGtwSGVjMkl4dU53aVFOckRYdTBPWlZBCnlKODByNk5DNm9VaTB3T1krdUhS
        OEVySDBUaTl3K0x2YnVLUmJCRnNHRzAKLS0tIHRBMEZ3bHFhZ1lzRHlxZDlkM0VY
        a1ErdjIxN29MblJqekVKU2VlUmRLNEkKjJI0kvgNMjsv3+jtB7Dehg0h9aLFwD0r
        dbhShdSVsi4PCqfdKyKRiIs3rCMtxZAxngT+JeHNrRFeN9aVSfyzPw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T20:02:58Z"
  mac: ENC[AES256_GCM,data:lGFqvOVn1hDFa8MZlmZPTbo9BS4eR1DWe7pT/tvLiiLiOpiW8gN4gmukcW34h+KOJ2quFbB2rdaYyjj1UbDpbgUArwtLKHa9Q7XoXsV7QxdNuRx2Oi/B1OGjHZ63pXVRqdMltwrCE4hjH9o/MUQNWQCZKjCDfE07OA0yigk4KJ4=,iv:23RjtrkVfWqZ+PoHq+myX0J75w9kB02r3+P3ICmDM1c=,tag:1NJkoxtfHqKSC/ZUHtOI2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
