---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app spoofdpi
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: spoofdpi
  values:
    controllers:
      spoofdpi:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/unmedius/spoof-dpi
              tag: latest@sha256:a3b54ac4bbccadec89e64499d1343c89f10f977a7eb2ff7b53bcc2592e916b1d
            resources:
              requests:
                cpu: 15m
                memory: 56Mi
              limits:
                memory: 256Mi

    service:
      app:
        controller: spoofdpi
        ports:
          http:
            port: 8080
