---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
components:
  - ../../flux/components/common
resources:
  - ./reloader/ks.yaml
  - ./intel-device-plugin/ks.yaml
