---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mssql
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      mssql:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: mcr.microsoft.com/mssql/server
              tag: 2022-latest
            env:
              ACCEPT_EULA: "Y"
              MSSQL_PID: "Developer"
              MSSQL_ENABLE_HADR: "1"
              MSSQL_AGENT_ENABLED: "true"
              MSSQL_DATA_DIR: "/var/opt/mssql/data"
              MSSQL_LOG_DIR: "/var/opt/mssql/log"
              MSSQL_BACKUP_DIR: "/var/opt/mssql/backup"
            envFrom:
              - secretRef:
                  name: mssql-secret
            resources:
              requests:
                memory: 1Gi
              limits:
                memory: 2Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          tcp:
            port: 1433

    persistence:
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /var/opt/mssql
