# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-valkey
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      immich-valkey:
        containers:
          app:
            image:
              repository: docker.io/valkey/valkey # https://github.com/valkey-io/valkey-container/issues/17 Need move to ghcr.io
              tag: 8.0.2
    service:
      app:
        controller: immich-valkey
        ports:
          http:
            port: 6379
