---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  TIMEZONE: Asia/Ho_Chi_Minh
  GATEWAY_VIP: 192.168.1.100
  CORE_DNS_VIP: 192.168.1.101
  ADGUARD_HOME_LB_VIP: 192.168.1.102
  LB_POSTGRES: 192.168.1.103
