# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings-secrets
data:
    MAIL_HOST: ENC[AES256_GCM,data:sR0v6Rsm8fBFlkfE/mk=,iv:j7PJdAA4zcguM/j7BD6zOXGxK44ZLsJLaZMmGbrq0NU=,tag:Imfk40V9AvEPWfs1CqwDgQ==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:qpjn,iv:xD1cbqT0bQBdsBY+DJXoSH2OrywQ38785pSo4QPsCaE=,tag:kQHwfBP0HFUF6DOK9St+wA==,type:str]
    MAIL_SENDER: ENC[AES256_GCM,data:ZvL2PdmBB4q87W1Y/k7EqoAxZ6ZUqA==,iv:N0b9RHR3cHQMyNIMYonh3wSTh2Py72ATuRZzh5gKnos=,tag:Km5k/NbbOrn+48uT3A0FyA==,type:str]
    MAIL_SENDER_NAME: ENC[AES256_GCM,data:xEM4dDVMAgLpYAo=,iv:C1L+PnfdnV8/PdGjA8IsEPrTZ5ca1SEV/wynVOiRtJY=,tag:ReGZrVDh6/tQ1hm1ZApQOQ==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:ui///WBefNfLUWLPg+WpVngrUQ==,iv:U6+GSBb96vNgU9aH4FUujXytHXpUN1VrJuaD5v6FyBY=,tag:uAH+tGtSUJohr2iHPrJnnQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:WIuaQCiSgaHVdcOLqhxWQeucNw==,iv:jWiR+snzrht6hi+DVKCar/PgtGS36w+3tkp8wI9e/oU=,tag:0BmyzbhtiIrpC+zYXMjyFQ==,type:str]
    VAULT_ADMIN_TOKEN: ENC[AES256_GCM,data:K2JCNCt+Rk+Q3p6b6u7kitS0L1po4eM/TlvZWDatSiSB6UkMGAPU3zRr+oHguqeZM7oQ9R0zreOXG/xDiLHgzftfjZEJYD7nv3ivgfQ7SlOqSPTA1bQA9Szn2ljGc7/5GCga/C2endxNJoYJl8sPFqKtBqCLyYOD9MPZ8G1BIOiEGBrS+reUbW0GeQ==,iv:VVyZFvjAcwNMNp7+B0zvf+nU5zCYYJi7D7EBoeNuWJc=,tag:i1qPihFWbhgJ6ucD2LuGOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdTVrUlBFVmxuRTQya0dJ
            MEZLNDRWTjRIbTlMVWlGZTF6S1NsNmo4Z25JCkVSTGpJYmJkZWdOSGpha3hsYWdN
            amRhNDRqM00wTWtUUVhwQ21VVG9hb2cKLS0tIHk1bGVrUG0xTmVJeVEyYWhEclJt
            VVdhdENsamlLZnNIc0Y0NlNXY3NKa28KCeQWkBmkt/10FnHwsOoMtA9yaZEIMPyG
            dzaDHefz1vJE5Bt6JvBLWMxNFDsdBC0d7rknKSwCMRbrMLINbVbNqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T20:45:09Z"
    mac: ENC[AES256_GCM,data:CPXHLnoSH0qT+/aV+zqMa23CxP/OrQIPEgaamUt8oyPykIhg4h8Yym5xxTmjPtJv8T9YNdns4k4tzHr1WeVHS2MJrGs0puaqCDy7TXgW6W1/k9Wv4CiCgFsFj/KPw1zWtDOGClKD8QNqPIud4ViCsODd16xTPwBLyOw4jLLsm+Y=,iv:BYv9RH1g0VmrIiQYiMkK8BxicrmPq1YrA87rrkrA0cY=,tag:VpSxNsduVsB7w6lT6dzffA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
