# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:28SKoAZIneQ2ztQ4x6eP5g==,iv:Y1wW+9SrI/IQyp9O+3PO3fiMxPKP4NXjLui2FpRM3qk=,tag:xJpAnpkg9e5Kc3lJwV7kHg==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:XKzt/EjgnWfjAQTXACuOXZBNlH6sE1T9ImrhON4+3JI4/P9d,iv:QnPv+wW/ppfCd9jD11qQoGehiCFlmJHDKVeneB4bb3w=,tag:4Hb2Vi0EYXdnlIvX5zqA+A==,type:str]
sops:
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTlhEYWIrbnphcTR4N3pR
            N2xuaVNLSnRleTFwTVdCQm13TnBuTGVLeG5RCnk1QXN5QS8zMHdrbVh3MUtXdXEv
            WUw2UjJmb2xFcWxsUm5NUU83dzZnaG8KLS0tIG43QWw4Q0FuL0hOVW0vTXZtV2k3
            ZVBoQWZtbTN5VGlwNzBLeTNZNkp6c1kKj0R6lTQrUU4J0RdRgMj/aGYkylNgXaFK
            JvSm2HGBZJu1pmx/j0lVRc/EPaylprRodVdyoM0U1IbRnaFr60TDEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-04T10:23:02Z"
    mac: ENC[AES256_GCM,data:2XY8h5Et8TxDNdK4itlXMTQE09Ik+bJV1rvTbqHOTVg4l2w3xsJ08Dw4Nd2Wlt/6C84Nk91FHP6Y/lIh/wKlxgiRMdbuwDR93abysvWZtfe4/A1Y9onwg/b570NUW+r1DI+OGbsxOZDiAXPK9qGuuHJNhGUrh+Q/omPAHPTLqcU=,iv:5C7GVeWkiuudRL7AvRn44m1/e+H/72sGjZMLx1QRrcY=,tag:456kjXu0OJ2SuswI6vqJgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
