# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:BMtkkzca8ulQpuimfsE36dbT8rSIHEyKAeFNu+rlTiJwLw7oS1Q2pzXQBhlWPWDnMKfXg4zuvI5SKffESFuS3PT87o2fNdEB3Jzi,iv:GMFUM8XtpI9vveC5i3pxCHH6N5UZRcnhrXbNdczhuGY=,tag:3VGMPtwyf+1aPhmVNl9NXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRGoyNllValZQdFRpemt6
            UUJ0K1cvSUxmQlFhcHhwZ0g0R2o3ak5vQVZzCjRLcUVYQjRIMnJROWxYNkFDMUkr
            Z0wyM3N5MWNSLzBsTXNHdzFjQm0yNTgKLS0tIHAyaEc5ejJnNGl3dXQzNXZEaytX
            c3RZQllpSmlDd2MzWGdwSklFVUcwOUEKQxIPx4ZOBoqL+HL/dBM77KH/NRm8i7W/
            Qz6UwWf5KiefhxQ3NKYLXzpT0P3YgPPD3oLS031aoh+s3bjKUZrq7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T21:50:06Z"
    mac: ENC[AES256_GCM,data:z2safl5unfYSsn3Q9pFXMr2GKfzEQN8KqTIT0K4IqmyKWi52FqfYeqKA+g8tn4dAzpC5XgSKdRN1AcXmx/ippHwBFDRfslP0X4+DutkzXU6farCU5frPPxGvP/fNEqY72kPsjO3EKevK25LA6ABDXEM+7J2JvYfaSS1BuUTX12E=,iv:GTTnyUEo+zUusa+vHOBE9F73ey2sHlphmXxsuVB7fHs=,tag:guHdZAa3aNOf5j1mRmHJ1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
