---
# yaml-language-server: $schema=https://schemas.tholinka.dev/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: postgres-${OWNER}
  namespace: postgres
spec:
  cluster:
    name: postgres-cluster
  name: ${OWNER}
  comment: '${APP} user'
  login: true
  superuser: false
  databaseRoleReclaimPolicy: delete
  disablePassword: true