---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr_anime:
    base_url: http://sonarr-anime.download.svc.cluster.local:8989
    api_key: !env_var SONARR_ANIME_API_KEY
    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    custom_formats:
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0

      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0

      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b3
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0

  sonarr_main:
    base_url: http://sonarr.download.svc.cluster.local:8989
    api_key: !env_var SONARR_API_KEY

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p

    custom_formats:
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p
            score: 0
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

      - trash_ids:
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: WEB-2160p

radarr:
  radarr_main:
    base_url: http://radarr.download.svc.cluster.local:7878
    api_key: !env_var RADARR_API_KEY

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      - template: radarr-quality-definition-sqp-streaming
      # 2160p
      - template: radarr-quality-profile-sqp-1-2160p-default
      - template: radarr-custom-formats-sqp-1-2160p

    quality_profiles:
      - name: SQP-1 (2160p)
        # min_format_score: 2000

    custom_formats:
      - trash_ids:
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
        assign_scores_to:
          - name: SQP-1 (2160p)

      - trash_ids:
          - b17886cb4158d9fea189859409975758 # HDR10+ Boost
          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
        assign_scores_to:
          - name: SQP-1 (2160p)

      - trash_ids:
          - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: SQP-1 (2160p)
