# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: radarr-anime-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:d7vGINN1vwXCpIyH1fMZeMhGZS7e1/rhHDxCYtRN01M=,iv:3HFiY9AisQnP6QaUvkmxQ+dWGxrI3UTGRYUTllaJgPU=,tag:RKIvcx30utBTQnBAmyjjZA==,type:str]
  RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:B/FoLTIabTd4yWGJA9kJdaeH4X4YefGwjo5OEVBku2H2lnIY0aU=,iv:2WfEfh7dmWJ2ORkAVpL1oov0NBW473tOjFmRj5HwhmQ=,tag:mMjWZqUkklndnM6C9uWmRQ==,type:str]
  RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:beSOeA==,iv:LTbAnfP35oLkTmsJTTodS1eGd+0dAwbaJtDO0fXroCw=,tag:hAQxXGREJrY5jl0UjdJesg==,type:str]
  RADARR__POSTGRES__USER: ENC[AES256_GCM,data:IwG5UCLP/BBE3mc3,iv:7vwHUjJdtpGCEcZRFgIJveYs/JtRNs5tAQJ2iucuJoY=,tag:+/JSxYDyPUXhwKuWdTgkXA==,type:str]
  RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:btNuRBQj02Pma9+7W1pRVkwdr6vLKyO75boOzJOh12Wp2qlT7xz9l7gs,iv:f6+2sweDZxsujtawEyr3wITVHX5hg+JhyCDcLAtw40g=,tag:7MZRK8vie16K3vgKE7NYlw==,type:str]
  RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:oD5HGmaz/8LRG/FngBUozZU=,iv:C5WPsLdOcTBdUcT2AwhOErkiTFdufrRT+xaG7Ma1pTc=,tag:xpavJPTAVvXmDOZVnUYEUw==,type:str]
  RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:98lJ6z7xm8VfAN+lylqVhw==,iv:TWlF1MbDUxwfF1BN8qZYYdmdulb5eGvPhNIqYBhFULA=,tag:fgwaRECM3xQprKivNx0WUA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:O9/0lJqAeJkrKEhxwggXfQvqVifsQP3r3+dQa653+gCfog==,iv:jgpzFutQV6rCyY/xXxMvqddcTH/sTe5rk9AgHxrg0W8=,tag:7JYO0MClvDDXuTfqerm/cg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:UkgNO5wRyRVlubJcJNJvySw9WpEbi/YQ2UfKgpqjCB0f+/VRLq8=,iv:BscAIN0F0JKLuVGwW9zagi2WPhvJaK/pCd2X08drKNk=,tag:66Fv+qZS/b6MxZob1KWNXA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:dPy+i2NJAFIUoXuD,iv:OHe+aRK2h/sZFeY5/05RRW8mHUvHBlYtpMf7qzOI6mM=,tag:d4dti0NfhxsuIDDL2QwLjg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:orcEErKiErTCzC8zvUNKHKWcZybjx6gkmQDyNTQCxdDSTqu42JNulb35,iv:9x0VXmzjFERXcl96CMm44Qg0/9eEFq97PUsk8uqQ+Tk=,tag:U8V/HWOINZThfhhyVPzYJQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:sjKeVygcrFod13JfHQuzzKSlpDKC7I8B91oSpf6naMFWH06RIIxtZeYbQZQ=,iv:kvN6ovyZmfROJZr1O0j3PmV0DeJ4LPeLePGTDP+BFcU=,tag:1C51iL/5FVbTrZLgL6u4VQ==,type:str]
sops:
  age:
    - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUzJJdVZxTElhMVk3N1BN
        V1ovVW80cXlqdEdpYzhTWktDdDMzOVN2aHpBCjIzSk1OTVAxa0JyVGpmQmdFS2c2
        aEY1QnFKeklUdktJeXF0Mmg1WmhpMkUKLS0tIFFJLzRGZ2VLYlZJSWQzd1E5ZFM1
        YjZWaUI2d2pkcDROcnJwY1h1a1JuL00KlI+5a6NeGtyCKZG5vDPSUMSiEY4ld7Wt
        qUDaahmakqCGIgatPZkIkT28lrjbl+FbbS+1HR7Lzg2iDKlLkcqqRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T09:56:11Z"
  mac: ENC[AES256_GCM,data:CmPSucVCRY8XSROdMLzxU9OluL3EpWeiLozJxBAC8X5lJqsV07/wQUVjg6ng6Ei3GcJgqFyrv50eqipF0ZuWaWSGsojYqBb6ho0Eyb0kAUqj5nPJHmX8wkCy6jc3XmWT+t5Yn6CFnUm9e+iQUkbaQPFaDhYvH0+gL5AQjyo5RpY=,iv:XLhqru3Kud7WBLlrSOeAl+g2LTKdcx5lLzb3Jj2Z9MU=,tag:I+IEOYZzu/yPwZYAwfHR2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.0
