# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: radarr-anime-secret
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:d7vGINN1vwXCpIyH1fMZeMhGZS7e1/rhHDxCYtRN01M=,iv:3HFiY9AisQnP6QaUvkmxQ+dWGxrI3UTGRYUTllaJgPU=,tag:RKIvcx30utBTQnBAmyjjZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUzJJdVZxTElhMVk3N1BN
            V1ovVW80cXlqdEdpYzhTWktDdDMzOVN2aHpBCjIzSk1OTVAxa0JyVGpmQmdFS2c2
            aEY1QnFKeklUdktJeXF0Mmg1WmhpMkUKLS0tIFFJLzRGZ2VLYlZJSWQzd1E5ZFM1
            YjZWaUI2d2pkcDROcnJwY1h1a1JuL00KlI+5a6NeGtyCKZG5vDPSUMSiEY4ld7Wt
            qUDaahmakqCGIgatPZkIkT28lrjbl+FbbS+1HR7Lzg2iDKlLkcqqRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T13:58:02Z"
    mac: ENC[AES256_GCM,data:yXQ+McCKUJcOGZjldhxpkm/oIlO+mHxJKpXGhBOTnNR9rVFlgpEuH3nID2PyKiogbCb88ubocE0U5PiFNf+WgNxM7VnBTNQDpVOSAkgLAE0bdaY6RmkoHf4z0iHRbu5RdCa35ZZv3FJ5fCBojYOQuPb51hMqSVo/+R+pYNBd1Hs=,iv:QCyvB8yPG2FCCMTMESIeR+TxwTZdunxWIV82IaU2TLU=,tag:r/l7IM0Qw5J01P0eIie1iQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
