---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
spec:
  components:
    - ../../../../components/gpu
    - ../../../../components/kopiur/backup
    - ../../../../components/zeroscaler
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
    - name: kopiur
      namespace: kopiur-system
  interval: 30m
  path: ./kubernetes/apps/media/jellyfin/app
  postBuild:
    substitute:
      APP: jellyfin
      KOPIUR_CAPACITY: 25Gi
      REPOSITORY: nas
      COMPRESSOR: zstd-fastest
      ZEROSCALER_TARGET: jellyfin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
