---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard-home-route
spec:
  parentRefs:
    - name: internal-gateway-cilium
      namespace: network
  hostnames:
    - "adguard-home.${SECRET_DOMAIN}"
  rules:
    - backendRefs:
      - name: adguard
        port: 3000
