apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ${APP}-restic-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Okt6kgECjd+SsP/3bSbBUfwUI2U=,iv:meE34/I3ZcOe6FbOflnIC1QMcfSHXHSlzCKPY+fUoCk=,tag:sKIDncwXRie6oAoWsmRfyQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yd8TcxIMXIAOpwATEw2b6+68dPJtI9iY1RCkMDsllzw873ZRqR5NNw==,iv:0BIms2gani5P5MLBOGdNaBefgBRsJCzuFGLodkGI9D8=,tag:1yV8Zp/bdC28Rt7PtNrkzg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:u8fK8JtDYql08lK0dDgN91NELnsgmF+V40ux2a9NDymW2GGwgQCtE8R/6hHw/4LSvaWRGw==,iv:hXq8AMp16yMZMKRyyWUamDCLK6mwMCJ4yrUsF5NpmbY=,tag:Z4p04KGYMSOTyytTtd+SYw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:rbqK35n1D+Vm,iv:W5J8Bmeq5ROPypKnuyANJfdHd20Fu6LoWNTMurbknLU=,tag:cWJajwTAutBXoR4o9ZJsgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb3VSK1V1SnJuZE9XMmVQ
            K05DenJtVHM0OFNLL1pmeUdEalZKZVhDdHhJCk90VmtDZFd5b3FOUEVnMklqYkFp
            WkJNRkV6K1lzTzdZdlJXUnJVbUNsVWcKLS0tIGtpc0Z0d0NyTEZpTVhwTzgwYXpD
            RCtMZmFnSXQ0SlV1S1YvNm1ab2hrRkUKvVuqhbn9xjpmiSYtKsG+7ryhznTqyqVt
            Lqfj3ReOnvOdAQl/8IKOS5sBdfpCpR2ULir+rAxxIBizQke0n9uOMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T15:11:56Z"
    mac: ENC[AES256_GCM,data:OvC6jXyqAli86yJlW5oBJ6TxOVRRzu4lCtEDnoGHKTsh41ftGD5gnXsbLAnHwi0CtWVl7EPox1Z8gGPPgeJ/JR2K2zJV9aJ0Clk7+u7p50feLUHeIjTLqhD3/zSDS9F8avSYsYsP3gVfukl69ytjswmJsSWcSfX0j/91fBXyVCs=,iv:ncbmXcqyf6vR/UU/QQotWrIMYmU+LvycRcHhcRT7HZo=,tag:ztBfhrNtRyL/mjlc6RKFdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
