apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ${APP}-restic-secret
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Okt6kgECjd+SsP/3bSbBUfwUI2U=,iv:meE34/I3ZcOe6FbOflnIC1QMcfSHXHSlzCKPY+fUoCk=,tag:sKIDncwXRie6oAoWsmRfyQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yd8TcxIMXIAOpwATEw2b6+68dPJtI9iY1RCkMDsllzw873ZRqR5NNw==,iv:0BIms2gani5P5MLBOGdNaBefgBRsJCzuFGLodkGI9D8=,tag:1yV8Zp/bdC28Rt7PtNrkzg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:AEWhJbxbypQNgroxPtpVzRc2gPBOhtBojJ8kM0IwaLT/mC1U6+zkFsZJaA==,iv:/2+HuUdlXCeRDJ0KWtt58BV/FG0PGZojnSGcseBusPA=,tag:kinYL/WX8M6BUiTd+kKvrQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:rbqK35n1D+Vm,iv:W5J8Bmeq5ROPypKnuyANJfdHd20Fu6LoWNTMurbknLU=,tag:cWJajwTAutBXoR4o9ZJsgQ==,type:str]
sops:
    age:
        - recipient: age1pu7fnazs9mnypwkh0zkayvd6dnvppr3nppadmyeun6w8nrmq3u3qxd6sfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb3VSK1V1SnJuZE9XMmVQ
            K05DenJtVHM0OFNLL1pmeUdEalZKZVhDdHhJCk90VmtDZFd5b3FOUEVnMklqYkFp
            WkJNRkV6K1lzTzdZdlJXUnJVbUNsVWcKLS0tIGtpc0Z0d0NyTEZpTVhwTzgwYXpD
            RCtMZmFnSXQ0SlV1S1YvNm1ab2hrRkUKvVuqhbn9xjpmiSYtKsG+7ryhznTqyqVt
            Lqfj3ReOnvOdAQl/8IKOS5sBdfpCpR2ULir+rAxxIBizQke0n9uOMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T16:28:52Z"
    mac: ENC[AES256_GCM,data:1BJnXl7rSuPEleJtkmcFRI/hmHOBYEsYArWoME5Hd79LxD7cgT0cBilWfeji2Q1OxoeXs4Plq6UJ3J2jYQ/CnmCjvZMfyJ9wdU18H0/Fhh87rjszSrkzGvMwjXq+3jcNTHdJqiag7B7Wroe8IrRA47IOsIsGwOxAKRZn6Uu4K1c=,iv:BsRp5v4hljfHr2ZsSPA0XEgZ31yoT3F+YExo4tlkuOQ=,tag:Lm2w20zjpJTvsw8lmarYdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
