---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway-cilium
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  addresses:
  - type: IPAddress
    value: ${GATEWAY_VIP}
  gatewayClassName: cilium
  listeners:
  - name: https
    protocol: HTTPS
    hostname: "*.${SECRET_DOMAIN}"
    port: 443
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: "${SECRET_DOMAIN/./-}-staging-tls"
          namespace: cert-manager
