---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: backube
  namespace: system
spec:
  interval: 30m
  url: https://backube.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: backube
      interval: 30m
  values:
    manageCRDs: true
    metrics:
      disableAuth: true

