apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway-cloudflare
spec:
  gatewayClassName: cloudflare
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
