---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
# components:
#   - ../../flux/components/common
resources:
  - ./namespace.yaml
  - ./certificates/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./adguard-home/ks.yaml
  - ./external-dns/ks.yaml
  - ./cloudflared/ks.yaml
